serialport:
  baudrate: 5760
  bytesize: EIGHTBITS
  parity: PARITY_EVEN
  port: /dev/ttyUSB0
  stopbits: STOPBITS_ONE
PricePerUnit:
  type_91: 37.93
  type_95: 36.5
  type_95p: 43.99
  type_B7: 0.0
  type_B20: 0.0
  type_DS: 0.0
  type_DSp: 46.21
  type_E20: 35.39
decimal_off_unit: 4
pump_grade:
  pump1:
    address: false
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_DSp
    grade2: type_E20
    grade3: type_95p
    grade4: type_DSp
    grade5: type_E20
    grade6: type_95p
  pump2:
    address: false
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_DSp
    grade2: type_E20
    grade3: type_95p
    grade4: type_DSp
    grade5: type_E20
    grade6: type_95p
  pump3:
    address: http://192.168.0.103:4000/api
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_95p
    grade2: type_E20
    grade3: type_DSp
    grade4: type_95p
    grade5: type_E20
    grade6: type_DSp
  pump4:
    address: http://192.168.0.102:4000/api
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_95p
    grade2: type_E20
    grade3: type_DSp
    grade4: type_95p
    grade5: type_E20
    grade6: type_DSp
  pump5:
    address: http://192.168.0.106:4000/api
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_DSp
    grade2: type_E20
    grade3: type_95p
    grade4: type_DSp
    grade5: type_E20
    grade6: type_95p
  pump6:
    address: http://192.168.0.105:4000/api
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_DSp
    grade2: type_E20
    grade3: type_95p
    grade4: type_DSp
    grade5: type_E20
    grade6: type_95p
  pump7:
    address: http://192.168.0.107:4000/api
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_DSp
    grade2: type_E20
    grade3: type_95p
    grade4: type_DSp
    grade5: type_E20
    grade6: type_95p
  pump8:
    address: http://192.168.0.108:4000/api
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_DSp
    grade2: type_E20
    grade3: type_95p
    grade4: type_DSp
    grade5: type_E20
    grade6: type_95p
  pump9:
    address: false
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_DSp
    grade2: type_95
    grade3: type_91
    grade4: type_DSp
    grade5: type_95
    grade6: type_91
  pump10:
    address: 127.0.0.1:46217
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_91
    grade2: type_95
    grade3: type_DSp
    grade4: type_91
    grade5: type_95
    grade6: type_DSp
  pump11:
    address: http://192.168.0.104:4000/api
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_91
    grade2: type_95
    grade3: type_DSp
    grade4: type_91
    grade5: type_95
    grade6: type_DSp
  pump12:
    address: http://192.168.0.101:4000/api
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_91
    grade2: type_95
    grade3: type_DSp
    grade4: type_91
    grade5: type_95
    grade6: type_DSp
  pump13:
    address: false
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_DSp
    grade2: type_95
    grade3: type_91
    grade4: type_DSp
    grade5: type_95
    grade6: type_91
  pump14:
    address: false
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_DSp
    grade2: type_95
    grade3: type_91
    grade4: type_DSp
    grade5: type_95
    grade6: type_91
  pump15:
    address: false
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_DSp
    grade2: type_95
    grade3: type_91
    grade4: type_DSp
    grade5: type_95
    grade6: type_91
  pump16:
    address: false
    decimal_preview_price: 2
    decimal_preview_unit: 3
    speed_profile: 1.1
    grade1: type_DSp
    grade2: type_95
    grade3: type_91
    grade4: type_DSp
    grade5: type_95
    grade6: type_91
